Gdpr notifications
gbif/registry pull request #48
Opened 2018-05-18 11:34 UTC by asturcon

depends on https://github.com/gbif/postal-service/pull/2

2018-05-22 12:34 UTC, fmendezh commented on registry-ws/src/main/java/org/gbif/registry/persistence/mapper/DataPrivacyNotificationMapper.java
> +import java.util.Map;
unused

2018-05-22 12:35 UTC, fmendezh commented on registry-ws/src/main/java/org/gbif/registry/persistence/mapper/handler/ContextTypeHandler.java
> + * Provides convertion from the key value pairs to HStore.
conversion or transformation

2018-05-22 12:40 UTC, fmendezh requested changes
only tiny observations

2018-05-22 12:46 UTC, asturcon commented
changes applied

2018-05-24 09:53 UTC, asturcon commented
Steps needed to release these changes:
- Merge changes of `postal-service`, generate version and add the new version to registry (postal service PR: https://github.com/gbif/postal-service/pull/2)
- Add the new properties to the `application.properties` for all the environments. I already created them for DEV (https://github.com/gbif/gbif-configuration/blob/edef706a5da140865cffb436ffb53e38bd258238/registry-ws/dev/application.properties#L85). 
  - The property `dataPrivacy.enabled` enables/disables the hook that checks if the notification was sent and sends the message to RabbitMq. 
  - The property `dataPrivacy.surety.mail.enabled` enables/disables the sending of the email.
- Create the new table in the database. The sql statement can be found on the file `053-add-data-privacy-notification-table.xml` in the `registry-liquibase` module.
- Generate new version of `registry-ws` and deploy it.
- Generate new version of `registry-cli` and release it. I created the necessary files only for DEV: 
  - Logback: https://github.com/gbif/gbif-configuration/blob/master/cli/dev/config/logback-registry-data-privacy-notification.xml
  - Yaml config: https://github.com/gbif/gbif-configuration/blob/master/cli/dev/config/registry-data-privacy-notification.yaml
  - Script to start the command: https://github.com/gbif/gbif-configuration/blob/master/cli/dev/bin/start-registry-data-privacy-notification). It may be necessary to add it to the start-all scripts too.

2025-12-04 10:38 UTC, closed without merging