adding source and sourceId filter to existing api
gbif/registry pull request #566
Opened 2024-04-22 11:46 UTC by ahakanzn

[[…/564](https://github.com/gbif/registry/issues)](https://github.com/gbif/registry/issues/564)

2024-04-23 09:39 UTC, marcos-lg commented
I think you forgot to update the gbif-api version to use the changes that you did in the gbif-api project? otherwise this branch doesn't compile

2024-04-23 09:49 UTC, marcos-lg requested changes

2024-04-23 09:49 UTC, marcos-lg commented on registry-persistence/src/main/resources/org/gbif/registry/persistence/mapper/collections/CollectionMapper.xml
> +        AND m.source = #{params.source}
You need to do a JOIN with the `master_sync_metadata` table to use those fields. The JOIN should be done only if these params are not null (you can check how the others are done)

2024-04-23 09:49 UTC, marcos-lg commented on registry-persistence/src/main/resources/org/gbif/registry/persistence/mapper/collections/CollectionMapper.xml
> +        AND m.source_id = #{params.sourceId}
same as above

2024-04-23 09:49 UTC, marcos-lg commented on registry-persistence/src/main/resources/org/gbif/registry/persistence/mapper/collections/InstitutionMapper.xml
> +        AND m.source = #{params.source}
same as in the collection mapper

2024-04-23 09:50 UTC, marcos-lg commented
Also, the query parameters are not being set to the request so they don't reach the service. You have to add the parsing to the argument resolvers(`InstitutionSearchRequestHandlerMethodArgumentResolver` and `CollectionSearchRequestHandlerMethodArgumentResolver`)

2024-04-23 09:52 UTC, marcos-lg commented
I suggest adding tests. For the persistence layer you can add tests to `InstitutionMapperIT` and `CollectionMapperIT`, for the service layer to `InstitutionServiceIT` and `CollectionServiceIT` and for the resource layer to `InstitutionResourceIT` and `CollectionResourceIT`

2024-04-24 12:17 UTC, marcos-lg commented on registry-integration-tests/src/test/java/org/gbif/registry/ws/it/collections/resource/CollectionResourceIT.java
> +    req.setSource(Source.DATASET);
just a comment for information, you don't have to change anything, in this case you are only testing that the parameters are being correctly serialized but not that they are being correctly set in the request because the service is mocked to return a response for every request. If the mock would return the response only if some specific params are set(for example, source dataset) then the argument resolver would be tested too

2024-04-24 12:20 UTC, marcos-lg commented on registry-ws/src/main/java/org/gbif/registry/ws/provider/CollectionSearchRequestHandlerMethodArgumentResolver.java
> +      searchRequest.setSource(VocabularyUtils.lookupEnum(sourceParam, Source.class));
Better to use here just Source.valueOf(). The VocabularyUtils.lookupEnum is used when we have values that don't match exactly with the enum names

2024-04-24 12:21 UTC, marcos-lg commented on registry-ws/src/main/java/org/gbif/registry/ws/provider/CollectionSearchRequestHandlerMethodArgumentResolver.java
> +    if (!Strings.isNullOrEmpty(sourceParam))
Also, let's put `{` and `}` in the ifs

2024-04-24 13:02 UTC, ahakanzn commented on registry-integration-tests/src/test/java/org/gbif/registry/ws/it/collections/resource/CollectionResourceIT.java
> +    req.setSource(Source.DATASET);
Yeah I was not sure about this part :) I have removed it

2024-04-24 13:02 UTC, ahakanzn commented on registry-ws/src/main/java/org/gbif/registry/ws/provider/CollectionSearchRequestHandlerMethodArgumentResolver.java
> +    String sourceParam = webRequest.getParameter("source");
Done

2024-04-24 13:02 UTC, ahakanzn commented on registry-ws/src/main/java/org/gbif/registry/ws/provider/CollectionSearchRequestHandlerMethodArgumentResolver.java
> +      searchRequest.setSource(VocabularyUtils.lookupEnum(sourceParam, Source.class));
Done

2024-04-24 13:31 UTC, marcos-lg approved these changes

2024-04-24 13:31 UTC, merged

2024-04-24 17:56 UTC, marcos-lg commented on registry-ws/src/main/java/org/gbif/registry/ws/provider/BaseGrSciCollSearchRequestHandlerMethodArgumentResolver.java
> +      request.setSource(Source.valueOf(Source.class,"sourceParam"));
I missed this. This should be Source.valueOf(sourceParam) , otherwise it doesn't work.